CREATE TABLE true_home.`T_USER_OTP` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `USER_ID` int,
  `OTP_VALUE` varchar(6),
  `IS_ACTIVE` tinyint(1) DEFAULT '1',
  `CREATED_BY` int DEFAULT 0,
  `UPDATED_BY` int DEFAULT 0,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  PRIMARY KEY (`ID`)
 ) ;

 CREATE TABLE true_home.`T_USERS` (
  ID int NOT NULL AUTO_INCREMENT,
  EMAIL varchar(100) NOT NULL,
  MOBILE varchar(100) NOT NULL,
  FIRSTNAME varchar(100) DEFAULT NULL,
  LASTNAME varchar(100) DEFAULT NULL,
  COUNTRY varchar(100) DEFAULT NULL,
  STATE varchar(100) DEFAULT NULL,
  CITY varchar(100) DEFAULT NULL,
  PINCODE varchar(100) DEFAULT NULL,
  IS_ACTIVE tinyint(1) DEFAULT '1',
  CREATED_BY int DEFAULT '0',
  UPDATED_BY float DEFAULT '0',
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
);

CREATE TABLE true_home.`T_LISTING` (
    id INT PRIMARY KEY AUTO_INCREMENT,
    ownerId INT,
    projectName VARCHAR(50),
    type VARCHAR(50),
    bhk VARCHAR(50),
    area DOUBLE,
    apartmentType VARCHAR(50),
    floor INTEGER,
    totalFloor INTEGER,
    description VARCHAR(500),
    city VARCHAR(50),
    postal VARCHAR(50),
    state VARCHAR(50),
    price DOUBLE,
    CREATED_BY int DEFAULT '0',
    UPDATED_BY float DEFAULT '0',
    CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ownerId) REFERENCES true_home.`T_USERS`(id)
);

CREATE TABLE true_home.`T_IMAGES` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_data VARCHAR(100),
    listing_id INT,
    FOREIGN KEY (listing_id) REFERENCES true_home.`T_LISTING`(id) ON DELETE CASCADE
);


CREATE TABLE true_home.`T_ORDERS` (
    id INT PRIMARY KEY AUTO_INCREMENT,
    accountId INT,
    productId INT,
    orderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY int DEFAULT '0',
    UPDATED_BY float DEFAULT '0',
    CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (accountId) REFERENCES true_home.`T_USERS`(id),
    FOREIGN KEY (productId) REFERENCES true_home.`T_LISTING`(id)
);

CREATE TABLE true_home.`T_WISHLIST` (
    id INT PRIMARY KEY AUTO_INCREMENT,
    accountId INT,
    productId INT,
    addedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY int DEFAULT '0',
    UPDATED_BY float DEFAULT '0',
    CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (accountId) REFERENCES true_home.`T_USERS`(id),
    FOREIGN KEY (productId) REFERENCES true_home.`T_LISTING`(id)
);
